export const ACCOUNT_LOADING = "ACCOUNT_LOADING";
export const ACCOUNT_ERROR = "ACCOUNT_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
