export const BOOKING_LOADING = "BOOKING_LOADING";
export const BOOKING_ERROR = "BOOKING_ERROR";
export const CREATE_BOOKING = "CREATE_BOOKING";

export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_BOOKING_DETAILS = "GET_BOOKING_DETAILS";

export const GET_APPROVED_PLAYER_LIST = "GET_APPROVED_PLAYER_LIST";
